#!/usr/bin/env sh

# Unload the macOS WindowManager process
#launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/refresh_displays.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/refresh_displays.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

yabai -m config external_bar all:0:0 \
	window_border on \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_zoom_persist off \
	window_placement second_child \
	window_topmost off \
	window_shadow float \
	window_opacity off \
	window_opacity_duration 0.15 \
	active_window_opacity 1.00 \
	normal_window_opacity 1.00 \
	window_border_width 2 \
	window_border_hidpi off \
	window_border_radius 11 \
	window_animation_duration 0.22 \
	active_window_border_color 0xffe1e3e4 \
	normal_window_border_color 0xff2a2f38 \
	insert_feedback_color 0xff9dd274 \
	split_ratio 0.50 \
	auto_balance off \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	\
	top_padding 10 \
	bottom_padding 30 \
	left_padding 10 \
	right_padding 10 \
	window_gap 15

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

# custom space allocations for specific apps
yabai -m rule --add label="Browser on space #1" app="Arc" space=1
yabai -m rule --add label="Alacritty Terminal on space #2" app="Alacritty" space=2 opacity=0.9
yabai -m rule --add label="KeePassXC on space #8" app="KeePassXC" space=8
yabai -m rule --add label="WezTerm on space #1" app="WezTerm" space=1
yabai -m rule --add label="Fork on space #3" app="Fork" space=3
yabai -m rule --add label="TablePlus on space #4" app="TablePlus" space=4
yabai -m rule --add label="Obsidian on space #5" app="Obsidian" space=5
yabai -m rule --add label="ChatGPT via safari on space #6" app="Safari" space=6
yabai -m rule --add label="Docker on space #7" app="Docker" space=7

# configurating the default layout
yabai -m config layout bsp

# Initialise workspace (open macOS apps)
$HOME/.config/yabai/initialise_workspace.sh

echo "yabai configuration loaded..woohoo"
